version: '3.9'

services:

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db
    ports:
      - 5432:5432

  cache:
    image: redis:7-alpine
    ports:
      - 6379:6379